### ISSUE TITLE
Not support windows7?

### ISSUE THREAD

**Issue by ahdung** [DarthAffe/ScreenCapture.NET#15]

**Comment by DarthAffe** [comment]
The current implementation is using the DesktopDuplication API that was introduced with Win8.
I'm currently reworking some basics to be able to add more capture providers in an easier way which would allow to add for example DX9 based capturing, but since that's performing way worse and win 7 is fully out of support anyway I'm not giving any promises regarding this.

**Comment by ahdung** [comment]
I see, thank you.
