### ISSUE TITLE
Multiple screen

### ISSUE THREAD

**Issue by jasonexe2000** [DarthAffe/ScreenCapture.NET#9]
When I use multiple screens to take screenshots, all of them except the first one show up as black screens.

```
IScreenCaptureService screenCaptureService = new DX11ScreenCaptureService();
IEnumerable<GraphicsCard> graphicsCards = screenCaptureService.GetGraphicsCards();
foreach (GraphicsCard graphicsCard in graphicsCards)
{
    IEnumerable<Display> displays = screenCaptureService.GetDisplays(graphicsCard);
    foreach (Display display in displays)
    {
        IScreenCapture screenCapture = screenCaptureService.GetScreenCapture(display);
        CaptureZone fullscreen = screenCapture.RegisterCaptureZone(0, 0, screenCapture.Display.Width, screenCapture.Display.Height);
        screenCapture.CaptureScreen();
        var image = Image.LoadPixelData<Bgra32>(fullscreen.Buffer, screenCapture.Display.Width, screenCapture.Display.Height);
        image.SaveAsJpeg("C:\\temp\\" + display.DeviceName + ".jpg");
    }
}
```

**Comment by DarthAffe** [comment]
That's an interesting issue. I've no idea why it behaves like this (and couldn't find anything in the docs about it) but it seems like the `LastPresentTime` for the first captured frame is always 0 if the capture was initialized after another call to `AcquireNextFrame` (even though they are not targeting the same display - I'd guess it's because they are on the same gpu but can't verify that).

There seem to be two ways to workaround that:
1. Call `CaptureScreen` twice before saving the image (to have an actual update after first that returns without a frame)
2. Register all zones before starting to capture them
